# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
        ('stu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='g_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grade.Grade'),
        ),
    ]
